### PR TITLE
Main major development - first tutorial finished

### PR DESCRIPTION
**Pull request by MartinKjunior**
Finished the first draft of the tutorial webpage. I've seen on analytics that many people have already visited it, hopefully now that it's sort-of useful the website becomes more welcoming and gains additional traffic.

If you know of anyone well-versed in git, please have them review my suggestions to see if I missed anything. 

A few things are hard for me to replicate from the point of view of a brand new user since a lot of my software is linked, therefore personalised.

**Make the button part of `Code` section as `OSIPI name` can have a lot of text**

- Removed the version number from website title (can be found in github link anyway)
- Finished first draft of How to contribute page #37 
- Added all buttons for all sections (let me know if it works once on the live site, it works locally for me) #41 
- Made the button thin #52 
image
Alternatively we can make it look like this. You should test both and see how they look in light/dark theme.
image
- Rewrote all equations in section G into MathJax #40 
- Finished section G (the google docs is incomplete here so I can't do more right now)
- Removed resources.md #39 
- Added a new page showing our quality of life features
- Fixed some equations and mistakes in Section P
- Added a `Source` link to every reference in dceliterature.md
- Changed favicon (this is the small icon inside your tab when you have multiple tabs open)
image
- Moved some images from `docs` to `docs/osipiImgs`
- Changed github icon to default github
- Added a `devcontainer.json` so people can use codespaces (response to [comments](https://github.com/OSIPI/OSIPI_CAPLEX/pull/49#issuecomment-1779796903))
- Added a note pointing people to contribution tutorial on the landing page.

### CODE REVIEW

**Comment by notZaki** [comment]
Excellent work! The contribution guide looks good. Here's my comments:

- For windows users, they might be able to install the require software through `winget` by running the following commands in a terminal
```
winget install -e --id Git.Git
winget install -e --id Anaconda.Miniconda3
winget install -e --id Microsoft.VisualStudioCode
```
- I think first time users might not be able to make a commit without configuring their git user name/email with
```
git config --global user.name "THEIR NAME"
git config --global user.email "THEIR EMAIL"
```
- Any thoughts about creating a codespaces template to allow contributions without needing to install anything? I made a quick attempt on [this forked branch](https://github.com/notZaki/OSIPI_CAPLEX/tree/devcontainer) and the codespace can be launched like in this gif
Codespaces
The codespace should have mkdocs already installed (if launched from that forked branch) and ready to go.

**Comment by MartinKjunior** [comment]
> Excellent work! The contribution guide looks good. Here's my comments:
> 
> * For windows users, they might be able to install the require software through `winget` by running the following commands in a terminal
> 
> ```
> winget install -e --id Git.Git
> winget install -e --id Anaconda.Miniconda3
> winget install -e --id Microsoft.VisualStudioCode
> ```
> 
> * I think first time users might not be able to make a commit without configuring their git user name/email with
> 
> ```
> git config --global user.name "THEIR NAME"
> git config --global user.email "THEIR EMAIL"
> ```
> 
> * Any thoughts about creating a codespaces template to allow contributions without needing to install anything? I made a quick attempt on [this forked branch](https://github.com/notZaki/OSIPI_CAPLEX/tree/devcontainer) and the codespace can be launched like in this gif
>   Codespaces
>         
>           [
>             
>           
>               Codespaces
>             ](https://user-images.githubusercontent.com/9019681/278105686-79d895b8-5b89-4e8e-941b-3890ca9ee3c0.gif)
>           
>           
>             
>               
>                 
>               
>               
>                 
>                 
>               
>             
>             [
>               
>                 
>               
>             ](https://user-images.githubusercontent.com/9019681/278105686-79d895b8-5b89-4e8e-941b-3890ca9ee3c0.gif)
>           
>         
>   The codespace should have mkdocs already installed (if launched from that forked branch) and ready to go.

Thank you for the feedback, this is very helpful as this project is the first time I've collaborated with others via GitHub and I'm learning everything on the go. 
* I went with full anaconda including navigator because I think the GUI of navigator may be helpful to people who might not be too comfortable with command prompt. However, I can add in your option since it only installs miniconda which some users may prefer. Does `winget install -e --id Git.Git` install Git for Windows? I'm also wondering if VSCode or anaconda come bundled with Git for Windows. I remember installing it when I was building some code with Visual Studio so I'm not sure about the details.
* This is true, I forgot about it because some time ago I managed to make it my email and name from my github were automatically used, but I'm not sure how to replicate that. The git commands can also be run inside VSCode so I can add that in.
* I've tried it out and it looks really good! Once it's fully set up and ready to go, we could add a tutorial on that at the top and then everything I wrote under it in case people want to work locally instead. Unfortunately I've never worked with containers before but I know they are popular and useful. I would like to ask you to make a tutorial on both how to create/maintain it as well as a little guide on the workflow including choosing the right branch and just whatever small differences there may be between working locally vs in a container. That could all be added into the How to Contribute page and I think it would pretty much be finished :)

**Comment by MartinKjunior** [comment]
@notZaki Just added in changes based on the first two points. Let me know if that's alright. I've also added in a note about the dev containers, happy to include more once it's done. I assume the `devcontainer` branch would eventually be part of the main github repo, so need to ask Ben to add that in (unless you have the privileges as well and can do it).

**Comment by MartinKjunior** [comment]
@notZaki I've noticed mkdocs-material also has a docker image, so could we use that for the devcontainer? https://squidfunk.github.io/mkdocs-material/getting-started/#with-docker

**Comment by notZaki** [comment]
`winget` can also install the full anaconda with
```
winget install -e --id Anaconda.Anaconda3
```
Depends on which the user prefers. 

Yes, `winget` should install git for windows, and the command is mentioned [on their downloads page](https://git-scm.com/download/win). It's been a while since I've had to do a fresh install of vscode, but I remember it asks something about git bash during the install, but not sure if it installs git too. 🤷 

The `mkdocs-material` addition to the devcontainer looks good to me. You could just create the `/.devcontainer/devcontainer.json` in this branch to try it out.

**Comment by MartinKjunior** [comment]
@notZaki I've just added in devcontainer.json. It works fine to create a codespace, `mkdocs serve` builds the local site, but for some reason opening it in a browser always fails for me on this branch. When I tried it on your branch, I could use `mkdocs serve` and see the local build just fine. I cannot commit anymore time to this project right now, so I'm leaving it here and once the pull request is accepted, trust that either you or Ben test the codespace and figure out what's going on. Maybe it's just an issue on my local machine. On the next 4.2 taskforce meeting you should also discuss codespace prices and configure maximum number of codespaces per user etc. since this is not a free service.

**Comment by MRdep** [comment]
A huge number of changes - checked and approved - Thank you Martin for your hard work.

**Pull request merged**
